nome=input("Digite um funcionário: ")
empresa=input("Digite a Instituição: ")
qtdefuncionarios=int(input("Digite a quantidade de funcionarios: "))
mediaMensalidade=float(input("Digite a média de mensalidade: "))
print(nome + "trabalha na empresa" + empresa)
print("Possui: ", qtdefuncionarios, "funcionarios.")
print("A media da mensalidade é de: " + str(mediaMensalidade))
print("=================Verifique os tipos de dados abaixo:===================")
print("O tipo de dado da variavel [nome] é ",type(nome))
print("o tipo de dado da variavel [empresa] é: ",type(qtdefuncionarios))
print("O tipo de dado da variavel [mediaMensalidade] é: ", type(mediaMensalidade))
